Config({
    "network-name": "العمودي ",
    "service-number": "775875761",
    "login-type": "user",
    "news-line": "...::::اهلا بكم في شبكتنا -   نتمنى لكم قضاء وقتا ممتعا ولاتنسى ذكر الله   كَلِمَتَانِ خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن: سبحان الله وبحمده، سبحان الله العظيم::::...",
    "input-type": "number",
    "input-autocomplete": "on",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "input-to-text-type-when": 0,
    "enable-hot-cookie": 0,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 2,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "app-store-status-button": false,
    "show-date-field": true,
    "loan-button": false,
    "app-store-base-url": "",// orWithProtocol: ex, http://192.168.10.10/app/ // leave it blank if locally
    "profiles": [
        {
            "price": "100 ريال",
            "time": "مفتوح",
            "transfer": "200 ميغا",
            "validity": "يوم",
        },
        {
            "price": "200 ريال",
            "time": "مفتوح",
            "transfer": "500 ميغا",
            "validity": "يومين",
        },
        {
            "price": "500 ريال",
            "time": "مفتوح",
            "transfer": "1.5 قيقا",
            "validity": " أسبوع",
        },
        {
            "price": "1000 ريال",
            "time": "مفتوح",
            "transfer": "3 جيجا",
            "validity": " شهر",
        },
        {
            "price": "2000 ريال",
            "time": "مفتوح",
            "transfer": "6 جيجا",
            "validity": " شهر",
        },
    ],
    "sell-points": [
        {"name":"المركز الرئيسي- العمودي للألعاب "},
        {"name":"مركز الفراولة "},
        {"name":"أجواء طيبة "},
    ]
})
